import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FooterPage from "@/components/Footer";

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas',
    weight: '400',
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bebasNeue.className}  h-full antialiased`}
    >
       
      <body className="min-h-full flex flex-col bg-[#202342] tracking-[1]">
       <Navbar></Navbar>

        {children}
        
        <FooterPage></FooterPage>
       </body>
    </html>
  );
}
